name: Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
             
      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: remove docker image
        run : |
          docker ps -aq | grep -v $(docker ps -aqf "name=nginx-container") | xargs -r sudo docker rm -f
      
      - name: Cross builder
        run: docker buildx create --name cross-builder --driver docker-container --use
      - name: Build Docker
        run: docker buildx build --platform=linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend --push .
      - name: Load Image 
        run: docker buildx build --platform=linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest --load .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest

      - name: SSH and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          password: ${{ secrets.HOME_SERVER_PASSWORD }}
          port: ${{ secrets.HOME_SERVER_PORT }}
          # script_stop: true
          script: |
            # React 애플리케이션 배포
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest
            sudo docker stop desplay-frontend || true
            sudo docker rm desplay-frontend || true
            sudo docker run -d -p 3000:3000 --name desplay-frontend ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest

      # # 도커 빌드 관련 셋업
      # - name: Set up Docker Buildx
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest . 

      # # 도커이미지 빌드하고 허브로푸쉬
      # - name: Build and push
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/desplay-frontend:latest
        